blueprints/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.exceptions import abort
from werkzeug.security import check_password_hash, generate_password_hash

from models.post import PostModel
from models.user import UserModel


bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        full_names = request.form['full_names']
        email = request.form['email']
        password = request.form['password']

        error = None

        if not email:
            error = 'Email is required.'
        elif not full_names:
            error ="Full names are required"
        elif not password:
            error = 'Password is required.'
        elif UserModel.find_user_by_email(email) is not None:
            error = 'User  with email- {} is already registered.'.format(email)

        if error is None:

         #   userModel = UserModel(full_names=full_names,email=email,password=enc_password)
            userModel = UserModel()
            userModel.password = UserModel.encrypt_password(password)
            userModel.full_names = full_names
            userModel.email = email
            userModel.save_to_db()
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        error = None
        user = UserModel.find_user_by_email(email)

        if user is None:
            error = 'Incorrect Email.'
        elif not user.authenticated(user.password, password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('index'))

        flash(error)

    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = UserModel.find_user_by_id(user_id)

def get_post(id, check_author=True):
    post = PostModel.find_by_id(id)

    if post is None:
        abort(404, "Post id {0} doesn't exist.".format(id))

    if check_author and post.user_id != g.user.id:
        abort(403)

    return post

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

blueprints/blog.py
import json

from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for,jsonify
)
from flask_uploads import UploadNotAllowed


from blueprints.auth import login_required, get_post
from libs import image_helper
from models.post import PostModel
from models.user import UserModel
from schema.post import PostSchema

bp = Blueprint('blog', __name__)

post_schema = PostSchema()
@bp.route('/post/json')
def allPosts():
    return {"posts": post_schema.dump(PostModel.find_all_posts(), many=True)}, 200


@bp.route('/')
def index():
    posts = PostModel.find_all_posts()
    return render_template('blog/index.html', posts=posts)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        image_file = request.files['file']
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        if not image_file:
            flash("Please Attach a file")
        else:

            folder = f"user_{g.user.id}"  # static/images
            try:
                image_path = image_helper.save_image(image_file,
                                                     folder=folder)
                basename = image_helper.get_path(image_path)
                userModel = UserModel.find_user_by_id(g.user.id)
                post = PostModel(title=title, posts=body, image_url=image_path, user_id=userModel.id)
                post.save_to_db()

            except UploadNotAllowed:
                extension = image_helper.get_extension(image_file)
                flash("file with extension {} not allowed".format(extension))

            return redirect(url_for('blog.index'))

    return render_template('blog/create.html')


@bp.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    post = get_post(id)

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            post.title = title
            post.posts = body
            post.save_to_db()

            return redirect(url_for('blog.index'))

    return render_template('blog/update.html', post=post)


@bp.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    post = get_post(id)
    post.delete()
    return redirect(url_for('blog.index'))

blueprints/contact.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)


bp = Blueprint('contact', __name__)
@bp.route('/contact')
def send_email():

    return render_template('contact/contact.html')

blueprints/profile.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from flask_uploads import UploadNotAllowed
from werkzeug.exceptions import abort
from werkzeug.security import check_password_hash, generate_password_hash

from libs import image_helper
from models.post import PostModel
from models.user import UserModel


bp = Blueprint('profile', __name__)

@bp.route('/user/<int:id>/profile',methods=('GET',))
def get(id):
    user = UserModel.find_user_by_id(id)
    if not user:
        flash("User doesn't exist")

    return render_template('profile/profile.html', user= user)

@bp.route('/user/<int:id>', methods=('GET', 'POST'))
def update(id):
    user = UserModel.find_user_by_id(id)
    if not user:
        flash("User doesn't exist")
    if request.method == 'POST':
        full_names = request.form['full_names']
        image_file = request.files['file']

        error = None

        if not full_names:
            error = "Full Names Required"

        if error is not None:
            flash(error)
        if not image_file:
            flash("Please Attach a file")
        else:

            filename = f"user_{g.user.id}"
            folder = "avatars"
            try:
                ext = image_helper.get_extension(image_file.filename)
                avatar = filename + ext
                image_path = image_helper.save_image(image_file,
                                                     folder=folder,name=avatar)
                basename = image_helper.get_path(image_path)
                user.full_names = full_names
                user.profile_pic = image_path
                user.save_to_db()

                #post = PostModel(title=title, posts=body, image_url=image_path, user_id=userModel.id)
                #post.save_to_db()

            except UploadNotAllowed:
                extension = image_helper.get_extension(image_file)
                flash("file with extension {} not allowed".format(extension))

            return redirect(url_for('profile.get',id=user.id))
    return render_template('/profile/edit_profile.html', user=user)

templates/profile/edit_profile.html
{% extends 'base.html' %}
{% block header %}
<h1>{% block title %}Edit Profile{% endblock %}</h1>
{% endblock %}
{% block menu %}

<ul class="sidebar-nav">
        <li class="sidebar-nav__item">

            <a class="sidebar-nav__link" href="{{ url_for('blog.index') }}">
            <span>Home</span></a>


        </li>
        <li class="sidebar-nav__item">
          {% if g.user %}
          <a class="sidebar-nav__link" href="{{ url_for('blog.create') }}">
            <span>Create</span></a>
          {% endif %}
        </li>
        <li class="sidebar-nav__item">
          <a href="#" class="sidebar-nav__link">
            <span>Work</span>
          </a>
        </li>
        <li class="sidebar-nav__item">
          <a href="#" class="sidebar-nav__link">
            <span>Contact</span>
          </a>
        </li>

         <li class="sidebar-nav__item sidebar-nav__item--active">
               {% if g.user %}
          <a href="{{url_for('profile.get',id=user.id)}}" class="sidebar-nav__link">
            <span>Profile</span>
          </a>
             {% endif %}
        </li>
      </ul>
      {%endblock %}
{% block header_menu %}

{% if g.user.id %}
<div class="header-menu">


          <a href="{{url_for('auth.logout')}}" class="header-menu__logout">
            <span>Log Out</span>
          </a>
        </div>

{% else %}
<div class="header-menu">

          <a href="{{url_for('auth.login')}}" class="header-menu__login">
              <span>Login</span></a>


          <a href="{{url_for('auth.register')}}" class="header-menu__register">
            <span>Register</span>
          </a>

      </div>

{%endif%}

{% endblock %}

{% block middle %}
  <div class="edit-scaffold">
        <form class="login-form" method="post" enctype=multipart/form-data >
        {% if user.profile_pic %}
<img src="http://{{request.host}}/static/images/{{user.profile_pic}}" alt="profile pic" class="profile-pic">

             {% else %}
         <div class="profile-placeholder-name">

             {% for s in user.full_names.split() %}

                 {{s[0]}}
             {% endfor %}

         </div>
        {%endif%}
         <input type=file name=file class="choose-profile-pic">
        <br />
      <input
        type="text"
        id="full_names"
        name="full_names"
       value="{{ request.form['full_names'] or user.full_names }}"
        placeholder="Enter your Full Names"
        class="login-form__input"
        required
      /><br />
      <input
        type="email"
        id="email"
        name="email"
        value="{{ request.form['email'] or user.email }}"
        placeholder="Enter your email"
        class="login-form__input"
        readonly
      /><br />
      <input type="submit" class="login-form__submit" value="Edit Profile" />
<br />

    </form>
 <a href="{{url_for('profile.get',id=user.id)}}" class="back-btn"><< back <<</a>


  </div>



{% endblock %}

templates/profile/profile.html
{% extends 'base.html' %}
{% block header %}
<h1>{% block title %}Your Profile{% endblock %}</h1>
{% endblock %}
{% block menu %}

<ul class="sidebar-nav">
        <li class="sidebar-nav__item">

            <a class="sidebar-nav__link" href="{{ url_for('blog.index') }}">
            <span>Home</span></a>


        </li>
        <li class="sidebar-nav__item">
          {% if g.user %}
          <a class="sidebar-nav__link" href="{{ url_for('blog.create') }}">
            <span>Create</span></a>
          {% endif %}
        </li>
        <li class="sidebar-nav__item">
          <a href="#" class="sidebar-nav__link">
            <span>Work</span>
          </a>
        </li>
        <li class="sidebar-nav__item">
          <a href="{{ url_for('contact.send_email') }}" class="sidebar-nav__link">
            <span>Contact</span>
          </a>
        </li>

         <li class="sidebar-nav__item sidebar-nav__item--active">
               {% if g.user %}
          <a href="{{url_for('profile.get',id=user.id)}}" class="sidebar-nav__link">
            <span>Profile</span>
          </a>
             {% endif %}
        </li>
      </ul>
      {%endblock %}
{% block header_menu %}

{% if g.user.id %}
<div class="header-menu">


          <a href="{{url_for('auth.logout')}}" class="header-menu__logout">
            <span>Log Out</span>
          </a>
        </div>

{% else %}
<div class="header-menu">

          <a href="{{url_for('auth.login')}}" class="header-menu__login">
              <span>Login</span></a>


          <a href="{{url_for('auth.register')}}" class="header-menu__register">
            <span>Register</span>
          </a>

      </div>

{%endif%}

{% endblock %}

{% block middle %}
<article class="profile">
      {% if user.profile_pic %}
<img src="http://{{request.host}}/static/images/{{user.profile_pic}}" alt="profile pic" class="profile-pic">

             {% else %}
         <div class="profile-placeholder-name">

             {% for s in user.full_names.split() %}

                 {{s[0]}}
             {% endfor %}

         </div>
        {%endif%}
    <div class="profile-details">
        <h2 class="profile-name">{{user.full_names}}</h2>
    <div class="profile-email">
        {{user.email}}
    </div>
        <div class="edit-btn">
            <a href="{{url_for('profile.update',id=user.id)}}" class="edit-btn">Edit Profile</a>
        </div>

    </div>

</article>
{% endblock %}