blueprints/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.exceptions import abort
from werkzeug.security import check_password_hash, generate_password_hash

from models.post import PostModel
from models.user import UserModel


bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        full_names = request.form['full_names']
        email = request.form['email']
        password = request.form['password']

        error = None

        if not email:
            error = 'Email is required.'
        elif not full_names:
            error ="Full names are required"
        elif not password:
            error = 'Password is required.'
        elif UserModel.find_user_by_email(email) is not None:
            error = 'User  with email- {} is already registered.'.format(email)

        if error is None:

         #   userModel = UserModel(full_names=full_names,email=email,password=enc_password)
            userModel = UserModel()
            userModel.password = UserModel.encrypt_password(password)
            userModel.full_names = full_names
            userModel.email = email
            userModel.save_to_db()
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        error = None
        user = UserModel.find_user_by_email(email)

        if user is None:
            error = 'Incorrect Email.'
        elif not user.authenticated(user.password, password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('index'))

        flash(error)

    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = UserModel.find_user_by_id(user_id)

def get_post(id, check_author=True):
    post = PostModel.find_by_id(id)

    if post is None:
        abort(404, "Post id {0} doesn't exist.".format(id))

    if check_author and post.user_id != g.user.id:
        abort(403)

    return post

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

blueprints/blog.py
import json

from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for,jsonify
)
from flask_uploads import UploadNotAllowed


from blueprints.auth import login_required, get_post
from libs import image_helper
from models.post import PostModel
from models.user import UserModel
from schema.post import PostSchema

bp = Blueprint('blog', __name__)

post_schema = PostSchema()
@bp.route('/post/json')
def allPosts():
    return {"posts": post_schema.dump(PostModel.find_all_posts(), many=True)}, 200


@bp.route('/')
def index():
    posts = PostModel.find_all_posts()
    return render_template('blog/index.html', posts=posts)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        image_file = request.files['file']
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        if not image_file:
            flash("Please Attach a file")
        else:

            folder = f"user_{g.user.id}"  # static/images
            try:
                image_path = image_helper.save_image(image_file,
                                                     folder=folder)
                basename = image_helper.get_path(image_path)
                userModel = UserModel.find_user_by_id(g.user.id)
                post = PostModel(title=title, posts=body, image_url=image_path, user_id=userModel.id)
                post.save_to_db()

            except UploadNotAllowed:
                extension = image_helper.get_extension(image_file)
                flash("file with extension {} not allowed".format(extension))

            return redirect(url_for('blog.index'))

    return render_template('blog/create.html')


@bp.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    post = get_post(id)

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            post.title = title
            post.posts = body
            post.save_to_db()

            return redirect(url_for('blog.index'))

    return render_template('blog/update.html', post=post)


@bp.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    post = get_post(id)
    post.delete()
    return redirect(url_for('blog.index'))

blueprints/contact.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)


bp = Blueprint('contact', __name__)
@bp.route('/contact')
def send_email():

    return render_template('contact/contact.html')

templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Create Post{% endblock %}</h1>
{% endblock %}
{% block menu %}

<ul class="sidebar-nav">
        <li class="sidebar-nav__item">

            <a class="sidebar-nav__link" href="{{ url_for('blog.index') }}">
            <span>Home</span></a>


        </li>
        <li class="sidebar-nav__item sidebar-nav__item--active">
          {% if g.user %}
          <a class="sidebar-nav__link" href="{{ url_for('blog.create') }}">
            <span>Create</span></a>
          {% endif %}
        </li>
        <li class="sidebar-nav__item">
          <a href="#" class="sidebar-nav__link">
            <span>Work</span>
          </a>
        </li>
        <li class="sidebar-nav__item">
          <a href="#" class="sidebar-nav__link">
            <span>Contact</span>
          </a>
        </li>
      <li class="sidebar-nav__item">
         {% if g.user %}
          <a href="{{url_for('profile.get',id=g.user.id)}}" class="sidebar-nav__link">
            <span>Profile</span>
          </a>
           {% endif %}
        </li>
      </ul>
      {%endblock %}
{% block header_menu %}

{% if g.user.id %}
<div class="header-menu">


          <a href="{{url_for('auth.logout')}}" class="header-menu__logout">
            <span>Log Out</span>
          </a>
        </div>

{% else %}
<div class="header-menu">

          <a href="{{url_for('auth.login')}}" class="header-menu__login">
              <span>Login</span></a>


          <a href="{{url_for('auth.register')}}" class="header-menu__register">
            <span>Register</span>
          </a>

      </div>

{%endif%}

{% endblock %}
{% block middle %}
  <form method="post" enctype=multipart/form-data class="create">

    <input name="title" class="post-title"
           value="{{ request.form['title'] }}"
           placeholder="Title of Post"
           required>


    <textarea name="body"
              placeholder="write something"
              class="post-area">{{ request.form['body'] }}

    </textarea>
      <input type=file name=file class="choose-file">
    <input type="submit" value="Save" class="create-submit">
  </form>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}All Posts{% endblock %}</h1>
{% endblock %}
{% block menu %}
<ul class="sidebar-nav">
        <li class="sidebar-nav__item sidebar-nav__item--active">

            <a class="sidebar-nav__link" href="{{ url_for('blog.index') }}">
            <span>Home</span></a>


        </li>
        <li class="sidebar-nav__item">
          {% if g.user %}
          <a class="sidebar-nav__link" href="{{ url_for('blog.create') }}">
            <span>Create</span></a>
          {% endif %}
        </li>
        <li class="sidebar-nav__item">
          <a href="#" class="sidebar-nav__link">
            <span>Work</span>
          </a>
        </li>
        <li class="sidebar-nav__item">
          <a href="{{ url_for('contact.send_email') }}" class="sidebar-nav__link">
            <span>Contact</span>
          </a>
        </li>
     <li class="sidebar-nav__item">
         {% if g.user %}
          <a href="{{url_for('profile.get',id=g.user.id)}}" class="sidebar-nav__link">
            <span>Profile</span>
          </a>
           {% endif %}
        </li>
      </ul>
{%endblock %}

{% block header_menu %}

{% if g.user.id %}
<div class="header-menu">


          <a href="{{url_for('auth.logout')}}" class="header-menu__logout">
            <span>Log Out</span>
          </a>
        </div>

{% else %}
<div class="header-menu">

          <a href="{{url_for('auth.login')}}" class="header-menu__login">
              <span>Login</span></a>


          <a href="{{url_for('auth.register')}}" class="header-menu__register">
            <span>Register</span>
          </a>

      </div>

{%endif%}

{% endblock %}

{% block middle %}

  {% for post in posts %}
<article class="post">
  <header>
    <div>
         <img src="http://{{request.host}}/static/images/{{post.image_url}}" alt="images uploaded" class="post_images">



      <h1 class="title">{{ post.title }}</h1>



    </div>

  </header>
     <p class="post-body">{{ post.posts }}</p>
    <div class="user-details">
 {% if post.users.profile_pic %}
<img src="http://{{request.host}}/static/images/{{post.users.profile_pic}}" alt="profile pic" class="profile-pic-sm">

             {% else %}
         <div class="profile-placeholder-name-sm">

             {% for s in post.users.full_names.split() %}

                 {{s[0]}}
             {% endfor %}

         </div>
        {%endif%}
      <div class="about-container">
          <div class="about">
               {{ post.users.full_names }}
          </div>
       <div class="time">
           posted on  {{ post.created_on.strftime('%Y-%m-%d') }}
       </div>

      </div>


        </div>
     {% if g.user.id == post.user_id %}
    <div class="post-options">
        <a href="{{ url_for('blog.update', id=post['id']) }}" class="edit">Edit</a>

        <form action="{{ url_for('blog.delete', id=post.id) }}" method="post">
    <input class="delete" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
         </div>

    {% endif %}
</article>
{% endfor %}

{% endblock %}

templates/blog/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Create Post{% endblock %}</h1>
{% endblock %}
{% block menu %}
<ul class="sidebar-nav">
        <li class="sidebar-nav__item">

            <a class="sidebar-nav__link" href="{{ url_for('blog.index') }}">
            <span>Home</span></a>
        </li>
        <li class="sidebar-nav__item  sidebar-nav__item--active">
          {% if g.user %}
          <a class="sidebar-nav__link" href="{{ url_for('blog.create') }}">
            <span>Create</span></a>
          {% endif %}
        </li>
        <li class="sidebar-nav__item">
          <a href="#" class="sidebar-nav__link">
            <span>Work</span>
          </a>
        </li>
        <li class="sidebar-nav__item">
          <a href="#" class="sidebar-nav__link">
            <span>Contact</span>
          </a>
        </li>
      <li class="sidebar-nav__item">
         {% if g.user %}
          <a href="{{url_for('profile.get',id=g.user.id)}}" class="sidebar-nav__link">
            <span>Profile</span>
          </a>
           {% endif %}
        </li>
      </ul>
      {%endblock %}
{% block header_menu %}

{% if g.user.id %}
<div class="header-menu">


          <a href="{{url_for('auth.logout')}}" class="header-menu__logout">
            <span>Log Out</span>
          </a>
     <form action="{{ url_for('blog.delete', id=post.id) }}" method="post">
    <input class="create-submit" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
        </div>

{% else %}
<div class="header-menu">

          <a href="{{url_for('auth.login')}}" class="header-menu__login">
              <span>Login</span></a>


          <a href="{{url_for('auth.register')}}" class="header-menu__register">
            <span>Register</span>
          </a>

      </div>

{%endif%}

{% endblock %}

{% block middle %}

      <form method="post" enctype=multipart/form-data class="create">

    <input name="title" class="post-title" placeholder="Title of Post"
      value="{{ request.form['title'] or post.title }}" required>

    <textarea name="body" class="post-area">{{ request.form['body'] or post.posts }}</textarea>
      <img src="http://{{request.host}}/static/images/{{post.image_url}}" alt="images uploaded" class="update-image">
      <input type=file name=file class="choose-file">
      <input type="submit" value="Save" class="create-submit">

  </form>






{% endblock %}